### ISSUE TITLE
Copy function for pages

### ISSUE THREAD

**Issue by andywenk** [melvinsembrano/cms-fortress#65]
I would be great to have the possibility to copy a page. I am not sure if this is an enhancement for cms-fortress or for comfy. I am thankful for any thoughts ...

**Comment by melvinsembrano** [comment]
My thoughts is this should be a Comfy enhancement.

**Comment by andywenk** [comment]
I expected that :D ha ha - ok - I will discuss it there. Thanks Melvin ;-)
