### ISSUE TITLE
Asset Path

### ISSUE THREAD

**Issue by marcusmoncayo** [melvinsembrano/cms-fortress#68]
Asset pipeline is loading assets from old path. This is causing 404's for asset requests.

**Comment by andywenk** [comment]
I am not sure if I understand the problem. Please explain it a bit more. If possible create a test case or add some code example. Thank you very much!

**Comment by zwzieg** [comment]
Comfortable Mexican Sofa has changed the asset path and CMS-Fortress is referencing the old path. If you declare comfortable_mexican_sofa as 1.12.3 it will work for now.

**Comment by zmckenzie** [comment]
Comfortable Mexican Sofa has changed the asset path and CMS-Fortress is referencing the old path. If you declare comfortable_mexican_sofa as 1.12.3 it will work for now.

**Comment by davidahopp** [comment]
In file _head.html.haml this change makes it work as there are only and admin assets now. I will do some more testing and fork and branch to issue a pull request for this.

```haml
%head
  %meta{'http-equiv' => "Content-type", :content => "text/html; charset=utf-8"}
  %title= settings.title
  = csrf_meta_tag

  = stylesheet_link_tag 'comfy/admin/cms/application'

  = stylesheet_link_tag "cms/fortress/admin_overrides"

  - unless default_theme?
    = stylesheet_link_tag "cms/fortress/themes/#{ theme_name }"


  = javascript_include_tag 'comfy/admin/cms/application'
  = javascript_include_tag 'cms/fortress/media'

  - unless default_theme?
    = javascript_include_tag "cms/fortress/themes/#{ theme_name }"


  = yield :head

  = render 'comfy/admin/cms/partials/html_head'
```

**Comment by andywenk** [comment]
There is no problem when you use the github master branch as your gem resource because there is already comfy 1.12.5 included as a dependency:

    gem 'cms-fortress', github: 'melvinsembrano/cms-fortress'

I think a new release is needed here. @melvinsembrano are you planning to release a new version?

**Comment by davidahopp** [comment]
On 1.12.5 they changed the entire assets folder structure seen [here](https://github.com/comfy/comfortable-mexican-sofa/commit/7f62385393be5532d1c3cc6df69c90cf230a0583)

**Comment by davidahopp** [comment]
I have issued a pull request with the updates I described above: https://github.com/melvinsembrano/cms-fortress/pull/69

**Comment by andywenk** [comment]
@davidahopp oh ... I completely missed that - my oversight. Thanks a lot!

**Comment by melvinsembrano** [comment]
Im currently running a few tests, will be releasing a new version later. 
Cheers @andywenk @davidahopp

**Comment by melvinsembrano** [comment]
A new gem version (1.3.6) is now released.  Closing ticket now.
Thanks @davidahopp @andywenk

**Comment by marcusmoncayo** [comment]
Thanks alot!
