### ISSUE TITLE
ComfyBlog compatibility

### ISSUE THREAD

**Issue by Amnesthesia** [melvinsembrano/cms-fortress#70]
It's possible that I'm just blind but, when using ComfyBlog there's no link to the blogs in the menu, but browsing to /admin/sites/:id/blogs work just fine and managing blogs from there does as well -- would be neat if this was in the menu

**Comment by andywenk** [comment]
Hi Amnesthesia,

you are in the cms-fortress repository. I guess you should ask this question in https://github.com/comfy/comfy-blog as it is an extension for Comfy. I personally never tried to use ComfyBlog with cms-fortress but it should work for sure. Is this where you try to use ComfyBlog?

All the best Andy

**Comment by melvinsembrano** [comment]
Hi @Amnesthesia,

You add any custom resources on the menu by modifying the 'config/initializers/cms_fortress.rb' file. Try  adding the following codes below and restart you app:
```
  config.content_resources << {
    name: 'blogs',
    title: 'Blogs', 
    path:  'comfy_admin_blogs_path'
  }
```
It will create a new entry under Contents menu.  You can also set the roles for Blogs by updating config/roles.yml file.

This feature is actually documented on item number 2 here (https://github.com/melvinsembrano/cms-fortress#adding-custom-role-details)

Regards,
Melvin

**Comment by Amnesthesia** [comment]
Oh damn! I'm sorry, I overlooked it as I interpreted 'custom role' as in privileges for users and not resources... Figured I was just being blind, felt like too big a thing to not be there :)

Thanks though and sorry for taking up your time
