### ISSUE TITLE
Comfy > 1.12.4 is breaking admin locally

### ISSUE THREAD

**Issue by andywenk** [melvinsembrano/cms-fortress#72]
Hi,

when upgrading comfy to > 1.12.4 I get an routing error for comfy css and js in cms-fortress admin. I am aware that @GBH changed the integration in 1.12.5 (https://github.com/comfy/comfortable-mexican-sofa/releases/tag/v1.12.5). Funny fact - in production it works. Locally I get:

    ActionController::RoutingError - Page Not Found at:  
    "javascripts/comfortable_mexican_sofa/application":
    comfortable_mexican_sofa (1.12.7) app/controllers/comfy/cms/content_controller.rb:64:in `rescue in  
    page_not_found'
    comfortable_mexican_sofa (1.12.7) app/controllers/comfy/cms/content_controller.rb:58:in   
    `page_not_found'

I have some custom js and css in app/assets/javascripts and app/assets/stylesheets/. I changed the paths there to: /app/assets/javascripts/comfy/admin/cms/ e.g. But still javascripts/comfortable_mexican_sofa/application is included in the markup <head>. I am not sure why this is and where to fix this.

Any help is highly appreciated as I want to upgrade to 1.12.7 and use redactor as the editor ;-)

**Comment by melvinsembrano** [comment]
Hi Andy,

I just tried building a new app with Comfy 1.12.7 and Fortress 1.3.6 and I cannot replicate the errors that you have.

I remember this file "javascripts/comfortable_mexican_sofa/application" but this was already removed few versions ago.

Regards,
Melvin

**Comment by andywenk** [comment]
Hi Melvin,

thanks for the quick answer. I have sorted that out. It was a strange error when trying to override the comfy css and js. I removed everything and I now have a default cms-fortress view. That's ok for now. But how do I override the styles in the admin correctly?

Thanks and cheers

Andy

**Comment by andywenk** [comment]
I think it should be https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/stylesheets/comfy/admin/cms/custom.sass but it does not have any effect

**Comment by melvinsembrano** [comment]
Hi Andy,

With the current version of layout there are two ways to include your custom css and js files. If you want your styles to be available to all admin pages, you can create a partial "comfy/admin/cms/partials/html_head" in which you can add your 'stylesheet_link_tags' and 'javascript_include_tags'.
Or you can use "content_for :head" for page specific styling.

I will take a look with the current Comfy Sass structure and will see what we can improve on this issue.

Regards,
Melvin

**Comment by andywenk** [comment]
Thanks for the help Melvin. I will create a wiki page how to get this running and link to it when created ...

Closing
