### ISSUE TITLE
flash messages are not shown in admin area

### ISSUE THREAD

**Issue by hafidi** [melvinsembrano/cms-fortress#77]
I've added some scaffolding to my app with:
rails g comfy:scaffold Location name:string distance:integer

but flash messages are not shown by creating or updating records!!

**Comment by andywenk** [comment]
@hafidi sorry for the very late reply. Is this still an issue?

**Comment by andywenk** [comment]
@hafidi quick reminder to my question. If this is not an issue, would you please close the issue?

Thx Andy

**Comment by hafidi** [comment]
I've solved the problem.

Thanks
