### ISSUE TITLE
Possible to hide sites dropdown from login?

### ISSUE THREAD

**Issue by tombroomfield** [melvinsembrano/cms-fortress#81]
Hi, Really love cms-fortress, thanks for all the hard work.
I was wondering if there was any way to hide the 'Sites' dropdown from the login screen. It is potentially sensitive which clients are using this system to have it displayed publicly.

Thanks,

**Comment by melvinsembrano** [comment]
Hi @tombroomfield,
On the next gem release the one email to multi-sites support will be disabled as default. You cannot see the Sites dropdown anymore on login window unless you enable back the feature by changing the configuration file.

**Comment by tombroomfield** [comment]
Hi @melvinsembrano - Thanks for the quick response. Is there at ETA on when that will become the default? Thanks again for your awesome work!

**Comment by melvinsembrano** [comment]
Unless anything comes up, the next release is on 9th of May. Cheers!

**Comment by melvinsembrano** [comment]
On version 1.3.12, site selector on login is now hidden by default. To enable the site selector just update config/initializers/cms_fortress.rb with the configuration below set to true:
```
config.login_site_selector = true
```
