### ISSUE TITLE
Have two different contents for one page?

### ISSUE THREAD

**Issue by NicoSa** [melvinsembrano/cms-fortress#83]
Hi, I'm new to fortress but it seems exactly like what I need. I'm currently trying to have two sections of contents for one page that I can then reference in different places in my layout. Is there an obvious way that I'm missing for doing this or is this something that I'd have to custom make, potentially send a PR?

**Comment by andywenk** [comment]
Hey @NicoSa,

did you find a solution? 

Cheers

Andy

**Comment by NicoSa** [comment]
Hi, yes, it was in the tags. I didn't realise that it changes the form accordingly when you add tags in the layout.
