### ISSUE TITLE
including ComfyBlog

### ISSUE THREAD

**Issue by mametz** [melvinsembrano/cms-fortress#85]
Is there a way to include the administration of other comfy plugins, like ComfyBlog? I installed the gem, but as cms-fortress is installed I can not access the "normal" CMS admin interface (which makes sense!)

**Comment by andywenk** [comment]
Hi @mametz,

hm - I don't understand that in depth. cms-fortress itself is just a "extension" of Comfy. It comes with a extended layout but you can also choose the Comfy layout. But that would mean, that some cms-fortress features / functionalities are not viewable. cms-fortress is overwriting some Comfy views so maybe it is simple to include the Blog stuff there. Could you give it a try?

Cheers

Andy

**Comment by bhushangahire** [comment]
I cant use default layout of Comfy not sure what is happening. Am I missing anything.

**Comment by melvinsembrano** [comment]
Hi @bhushangahire, you can refer the solution from here https://github.com/melvinsembrano/cms-fortress/issues/70 

Cheers,
Melvin

**Comment by andywenk** [comment]
@melvinsembrano you are so right ;-) +1

**Comment by bhushangahire** [comment]
Thanks will try that today.

**Comment by bhushangahire** [comment]
This works you can close this.
